### PR TITLE
USB ST-Link Debugger with USART Pass Through

### PR DESCRIPTION
**Pull request by ethanmpeterson**
Goal: Replicate the debugging capability of STM32 Nucleo development boards with full ST-LINK capability and Serial over one USB connection.

### CODE REVIEW

**Comment by ethanmpeterson** [comment]
Board Bring Up Progress: The debugger is fully working! The only snags in the process were software related. Unfortunately, STM does not open source their ST-Link firmware binaries. As a result, I have been unable to find a binary for the version of ST-Link firmware that has UART support (This is included on STM's nucleo board lineup, I am currently looking into pulling the firmware that way). However, I have found the binaries for normal ST-Link online. Using normal ST Link firmware, the debugger works as expected. While investigating how to get the ST-Link firmware with UART (called ST-LinkV2-1) I found an open source debugger project called black magic probe. With some small modifications to the pin assignments in their code, I got the open source firmware running on the custom debugger. This open source debugger also has UART pass through meaning we can debug and use serial via one USB port. I forked the firmware and added my pin assignment change. The fork is located at https://github.com/qfsae/blackmagic.

The debugger now does everything we need and can be integrated into future designs. I would still like to do a second fabrication run of the board to address the following issues:

- Incorrect footprint for the 2 pin headers (holes should be more spaced)
- Add silk screen to make hookup to target easier (label SWDIO and CLK)
- Replace reset jumper with a surface mount button.
- Remove regulator enable jumper

**Comment by llim1** [comment]
No DRC errors ❌ - _**USB connector footprint is < 0.2mm from edge of board**, pretty minor but does fail DRC on my system_
All SMD parts on one layer ✔️ 
IR Calculations for high current traces ✔️- _N/A_
Board is mechanically sound, dimensions are correct and component height does not create mechanical conflicts ✔️ 
IO ports and connectors double checked such that they are accessible when the board is fully assembled ✔️ - _good for this design_
No unconnected ground ✔️ 
Ground pour on top and bottom layers. 🟡 - _Only bottom layer ground pour is sufficient_ 
Stitching vias ✔️ 
Length matching for high speed signals and differential pairs ✔️ 
Proper filter capacitor placement for MCU layout (as close to the pin as possible and in the path of current flow) ✔️ 

**Other changes:**
- Bottom layer silkscreen appears to be backwards. 
- I like the bottom silkscreen as a reference though. If possible some abbreviated identifiers beside the header would be nice but space is a little tight. Not required
- Also not required but if you'd like to be fancy add the formula logo to the bottom silkscreen in the free space 🚗

**Comment by ethanmpeterson** [comment]
> No DRC errors ❌ - _**USB connector footprint is < 0.2mm from edge of board**, pretty minor but does fail DRC on my system_
> All SMD parts on one layer ✔️
> IR Calculations for high current traces ✔️- _N/A_
> Board is mechanically sound, dimensions are correct and component height does not create mechanical conflicts ✔️
> IO ports and connectors double checked such that they are accessible when the board is fully assembled ✔️ - _good for this design_
> No unconnected ground ✔️
> Ground pour on top and bottom layers. 🟡 - _Only bottom layer ground pour is sufficient_
> Stitching vias ✔️
> Length matching for high speed signals and differential pairs ✔️
> Proper filter capacitor placement for MCU layout (as close to the pin as possible and in the path of current flow) ✔️
> 
> **Other changes:**
> 
> * Bottom layer silkscreen appears to be backwards.
> * I like the bottom silkscreen as a reference though. If possible some abbreviated identifiers beside the header would be nice but space is a little tight. Not required
> * Also not required but if you'd like to be fancy add the formula logo to the bottom silkscreen in the free space 🚗

- Bottom silkscreen was in fact flipped (fixed now)
- For the reference silk screen next to the programming headers, I will try to add if I can fit it while having it be large enough for JLC PCB to print effectively.
- I would also like to add the formula logo, what file have you used for that on past designs?
- For the USB connector, the DRC error comes from the silkscreen outline being too close to the board edge. My only concern about moving it back further is that if the connector is too far back from the edge we may not be able to make a good connection with the USB mini cable. I suppose this issue depends on the cable, but I kept it right at the edge just to be safe. Let me know what you think.

**Comment by llim1** [comment]
Yeah I don't think the design rule violations are dealbreakers; since you have a board ordered already, if the connector is in a good spot then I'd say we're all good.  

For the logo I always lose the file we usually use. I'm pretty sure I always just end up pulling the first image that comes up when you google QFSAE... It's high res and has transparency, (https://myams.org/wp-content/uploads/2019/08/QFSAE-logo.png)

Other than that once you're happy with the cosmetic changes I'd say good to merge.

**Review by llim1 — APPROVED** [review]
LGTM

**Pull request merged**
