### PR TITLE
Altium tutorial

### PR DESCRIPTION
**Pull request by llim1**
Tutorial Layout for Altium.

### CODE REVIEW

**Comment by llim1** [comment]
@ethanmpeterson I think this should go into the onboarding-projects folder in #19, too.

**Comment by ethanmpeterson** [comment]
> @ethanmpeterson I think this should go into the onboarding-projects folder in #19, too.

Good idea, base this PR off the branch in #19. Place the tutorial PCB project in `onboarding/Q21`. Once it is in the right directory I think it is good to merge.

**Review by ethanmpeterson — APPROVED** [review]

**Review by ethanmpeterson — CHANGES_REQUESTED** [review]
Could you remove the copy of the project from the top level of the repository? It is currently in two places. Also, merge in the changes from master that have the onboarding folder, Q21 folder and related readme files

**Review by ethanmpeterson — APPROVED** [review]

**Comment by llim1** [comment]
Added the project description to the Q21/ readme, with some blank rows to add more projects in case some are unfamiliar with markdown tables.

**Pull request merged**
