### PR TITLE
BSPD Revision

### PR DESCRIPTION
**Pull request by llim1**

### CODE REVIEW

**Review by ethanmpeterson — CHANGES_REQUESTED** [review]
Note to migrate this project to the template and fill out on the checklist before merge. (Should also be fully tested first)

**Review by ethanmpeterson — CHANGES_REQUESTED** [review]
All important nets named **Maybe the nets here could use names. Anything with a test point should also have a net name to make it easier to figure out what you are probing.**

image

 
No spaces in net names (use underscores) **Looks good. Question: should we capitalize all net names?**


Net names do NOT begin with numbers or other special characters such as +-/\. This makes naming software variables corresponding to a certain net easier. **No SW here but may still be a good idea to be consistent with VCC12V instead of +12 for power rail naming.**


No 4 point connections **Looks good**


Short circuit protection via current monitor implementation or fuse, Specifically for power rails supplying expensive parts. **N/A**


No circuit compilation errors. **There are some errors here. We have pre-cleared the one where the op amp outputs are shorted together but the rest should be examined. Also has missing designators, go to Tools -> Annotation -> Annotate Schematics to fix this.**
 
Active low signals have _n at the end of their net name **Was our `flag_output` active low? If so, add the `_n`**


Differential pair nets are named with _P and _N endings. Both nets in the pair should also be marked with the differential pair schematic marking in Altium. **N/A**

Other Notes:
- You have normal text to mark DNP parts. Altium has support for DNP using design variants. This will help us with BOM management. https://www.altium.com/documentation/altium-designer/design-variants-ad?version=18.1

**Review by ryan-and — COMMENTED** [review]
- All important nets named. **Maybe the test point nets like Ethan said**
- No spaces in net names. 👍 
- Net names not beginning with numbers/special characters. **Change +12 and +5 nets to the VCC format** 
- No 4 point connections. 👍 
- No circuit compilation errors.
**Missing designators: 10msec delay cap, latch pulldown resistor, 10msec delay switch, LDO**
**Have we cleared _both_ the U8 and U6 op-amp shorts? (pretty sure both are fine)** 
**No driving source errors: I think they're fine? See [here](https://www.altium.com/documentation/altium-designer/workspacemanager-err-netswithnodrivingsourcenets-with-no-driving-source-ad)**
- Active low with _n. **Like Ethan said, double check** `flag_out`

Other comments
- U7, U4, and LDO are out of stock on Digikey but are available through Mouser if needed

**Comment by llim1** [comment]
> All important nets named **Maybe the nets here could use names. Anything with a test point should also have a net name to make it easier to figure out what you are probing.**
> 
> image

Good call, done.

> No spaces in net names (use underscores) **Looks good. Question: should we capitalize all net names?**

I don't think it matters if we do all caps or not, but whichever we go with it should be consistent. I have capitalized all nets now. 

> Net names do NOT begin with numbers or other special characters such as +-/. This makes naming software variables corresponding to a certain net easier. **No SW here but may still be a good idea to be consistent with VCC12V instead of +12 for power rail naming.**

True. Power nets renamed to VCC--V

> No circuit compilation errors. **There are some errors here. We have pre-cleared the one where the op amp outputs are shorted together but the rest should be examined. Also has missing designators, go to Tools -> Annotation -> Annotate Schematics to fix this.**

Only the multiple-output errors that we pre-cleared remain. There are warnings about pins having no driving source but I am not sure what to do about those and don't think they matter. Please correct me if I'm wrong!

> Active low signals have _n at the end of their net name **Was our `flag_output` active low? If so, add the `_n`**

Done. 

> Other Notes:
> 
> * You have normal text to mark DNP parts. Altium has support for DNP using design variants. This will help us with BOM management. https://www.altium.com/documentation/altium-designer/design-variants-ad?version=18.1

I considered creating variants but it seemed like overkill.. I have the component type set to (No BOM) so it will not appear in the BOM as seen in the pic below. Is there a reason to go the extra effort and set up variants? 
image

**Comment by llim1** [comment]
> **Have we cleared _both_ the U8 and U6 op-amp shorts? (pretty sure both are fine)**

Shorting the op-amp outputs together behaves like a logical OR, which is desired.

>   **No driving source errors: I think they're fine? See [here](https://www.altium.com/documentation/altium-designer/workspacemanager-err-netswithnodrivingsourcenets-with-no-driving-source-ad)**

That's reassuring, I am leaving them for now as they are just warnings.

> Other comments
> 
> * U7, U4, and LDO are out of stock on Digikey but are available through Mouser if needed

We have leftover stock from past production runs. Should be no problem

**Comment by ethanmpeterson** [comment]
> > All important nets named **Maybe the nets here could use names. Anything with a test point should also have a net name to make it easier to figure out what you are probing.**
> > image
> 
> Good call, done.
> 
> > No spaces in net names (use underscores) **Looks good. Question: should we capitalize all net names?**
> 
> I don't think it matters if we do all caps or not, but whichever we go with it should be consistent. I have capitalized all nets now.
> 
> > Net names do NOT begin with numbers or other special characters such as +-/. This makes naming software variables corresponding to a certain net easier. **No SW here but may still be a good idea to be consistent with VCC12V instead of +12 for power rail naming.**
> 
> True. Power nets renamed to VCC--V
> 
> > No circuit compilation errors. **There are some errors here. We have pre-cleared the one where the op amp outputs are shorted together but the rest should be examined. Also has missing designators, go to Tools -> Annotation -> Annotate Schematics to fix this.**
> 
> Only the multiple-output errors that we pre-cleared remain. There are warnings about pins having no driving source but I am not sure what to do about those and don't think they matter. Please correct me if I'm wrong!
> 
> > Active low signals have _n at the end of their net name **Was our `flag_output` active low? If so, add the `_n`**
> 
> Done.
> 
> > Other Notes:
> > 
> > * You have normal text to mark DNP parts. Altium has support for DNP using design variants. This will help us with BOM management. https://www.altium.com/documentation/altium-designer/design-variants-ad?version=18.1
> 
> I considered creating variants but it seemed like overkill.. I have the component type set to (No BOM) so it will not appear in the BOM as seen in the pic below. Is there a reason to go the extra effort and set up variants?
> image

Would prefer variants still as it makes it much more clear what is going on but this can work too. The use of variants also allows us to change the values of the parts and make substitutions more easily. Just a more powerful way to handle different skews of the same design.

**Review by ryan-and — APPROVED** [review]
- No DRC errors
        **Un-Routed Net Constraint** ✅ 
            It’s unhappy with the mounting holes. I don’t think this is really a problem.
        **Silk to Solder Mask** ✅ 
            It’s fine, all solder masks will be readable regardless. We can always just refer to the schematic as well.
- All SMD parts on one layer ✅ 
- IR Calculations for high current traces ✅ 
- Board is mechanically sound, dimensions are correct and component height does not create mechanical conflicts ✅ 
- IO ports and connectors double checked such that they are accessible when the board is fully assembled ✅ 
- No unconnected ground (remove dead copper button checked on Altium polygon object or add stitching via) ✅ 
- Ground pour on top and bottom layers ✅ 
- Stitching vias ✅ 
- Length matching for high speed signals and differential pairs **N/A**
- Proper filter capacitor placement for MCU layout (as close to the pin as possible and in the path of current flow) **N/A**

**Pull request merged**
