### PR TITLE
Spectrum analyzer

### PR DESCRIPTION
**Pull request by fabiansm5**
spectrum analyzer for can bus line

### CODE REVIEW

**Review by ethanmpeterson — COMMENTED** [review]
Great work on this!

Just a few questions / comments:

- Why tie an A/D input directly to GND through a 0 ohm resistor? I do not think we get any useful information out of sampling our ground reference but I could be wrong. Removing this would free up another AD channel.
- Ideally we have two free channels to sample CANH and CANL directly to try some digital signal processing in SW.
image
- Not sure what this is on the current measurement output of the sensor. No diode or series resistance is advisable since it will modify output voltage and make our back substitution in SW harder. Also think the 4.7 uF cap should be removed as it could reduce signal rise time / bandwidth of the sensor.
- Could also draw too much current from that output and lead to "brown out" issues maybe?
- Otherwise the current sense wiring is correct, great work.
image

- Nitpick: Power rail naming should be VCC5V as per our convention on other designs 
image

- Also may be helpful to name the nets in your LISN and other filtering circuitry to help when reading the layout of the board / debug.
- Overall, I think this schematic captures all the approaches you were looking at. Awesome job!

- In regards to layout, I think this will do the trick. Ryan will handle all the checklist work.
- Be sure to clear these DRC errors like the floating traces here:
image
- Overlapping silkscreen here:
image
- Bypass caps should be placed directly in the path of the flowing current:
image
- More silkscreen cleanup:
image
- Lastly, not sure how this happened, but there appears to be a mounting hole attached to the net of your current monitor:
image
- Nitpick: could we change the name of the project and pcb to be more descriptive instead of arduino shield template?
- Avoid 90 degree bends in the traces 
image

- I think this is all I have for now, please let me know if you have any questions about this review.

Ethan

**Comment by fabiansm5** [comment]
* Fixed the PCB layout, 
* Further conversation with Ethan ensured the current monitor was good originally.
* LISN still outputs negative impedance, and its high-frequency noise will not be collected to give space for raw CANH CANL inputs
* added CANH and CANL inputs to analog pins

**Comment by llim1** [comment]
Jumping in here with some action items:

* connectors J0, J1, and J2 are oriented facing inboard, which will make connecting wires more difficult: 
image
The wire receptacles should face out of the board. Always make sure to double check the 3D view if possible! 

* J3 takes a CAN bus differential pair. It would be good practice to route the signal traces going to AD4/AD5 as a differential pair as well, but don't worry to much about length matching.

* Otherwise, the only remaining change to resolve is this comment: 
> * Avoid 90 degree bends in the traces
>   image

Good work so far! If any questions just let me know. Logan

**Review by llim1 — CHANGES_REQUESTED** [review]
Jumping in here with some action items:

* connectors J0, J1, and J2 are oriented facing inboard, which will make connecting wires more difficult: 
image
The wire receptacles should face out of the board. Always make sure to double check the 3D view if possible! 

* J3 takes a CAN bus differential pair. It would be good practice to route the signal traces going to AD4/AD5 as a differential pair as well, but don't worry to much about length matching.

* Otherwise, the only remaining change to resolve is this comment: 
> * Avoid 90 degree bends in the traces
>   image

Good work so far! If any questions just let me know. Logan

**Review by llim1 — APPROVED** [review]
Looks good! 👍 Board is ordered

**Pull request merged**
