### PR TITLE
A2C Rev1 

### PR DESCRIPTION
**Pull request by ryan-and**
Schematic before PCB layout.

### CODE REVIEW

**Comment by ethanmpeterson** [comment]
All important nets named ✔️
No 4 point connections ✔️
Short circuit protection via current monitor implementation or fuse, Specifically for power rails supplying expensive parts **N/A**
No circuit compilation errors **There are some errors listed below**
- CAN differential net names (fix shown below)
- BOOT0 Pin is not connected, just wire it to ground with a pull down resistor. (10K is fine)
- **General Note:** Do not use spaces in net names. I will probably add this to the checklist but it seems to be hard to tell the difference between there being a space and no space at all.
- Bump R2 to a 330 Ohm resistor. 200 Ohms won't break the LED, but I have found that a bigger value is needed to keep the brightness down and make it easier on the eyes. Good rule of thumb is current through the LED being approximately 5mA.

Active low signals have _n at the end of their net name **N/A**
Differential pair nets are named with _P and _N endings. Both nets in the pair should also be marked with the differential pair schematic marking in Altium -> **They have the marking but the net names should end in _N and _P. Currently you have a SPACE characters followed by N and P.**

**Review by ethanmpeterson — CHANGES_REQUESTED** [review]
See above

**Comment by ryan-and** [comment]
- [x] CAN differential net names
- [x] BOOT0 Pin is not connected
- [x] Do not use spaces in net names.
- [x] R2 to a 330 Ohm

**Comment by ethanmpeterson** [comment]
> * [x]  CAN differential net names
> * [x]  BOOT0 Pin is not connected
> * [x]  Do not use spaces in net names.
> * [x]  R2 to a 330 Ohm

@ryan-and I cannot see these changes as I do not think they are pushed. Maybe just push them with the rest of the layout and I will take a look then.

**Comment by ryan-and** [comment]
Changes are not yet pushed. Once back in Kingston I will pushed the finished schematic and layout of A2C Rev1.

**Pull request merged**
