### PR TITLE
DevKit PCB

### PR DESCRIPTION
**Pull request by ethanmpeterson**
The DevKit PCB is an implementation of the CAN bus shield onboarding project. The PCB will mate to a NUCLEO F446RE board as a shield and allow the user to connect to CAN networks and do CAN software development.

### CODE REVIEW

**Review by llim1 — COMMENTED** [review]
Schematic looks good to me 👍

**Comment by ethanmpeterson** [comment]
> Schematic looks good to me

Awesome, I will go ahead and do a layout.

**Review by llim1 — CHANGES_REQUESTED** [review]
Checklist:
No DRC errors ✔️ 
All SMD parts on one layer ✔️ 
IR Calculations for high current traces 🟡 
The width should be large enough such that temperature increase for the expected current is no more than 5 to 10 degrees celsius ✔️ 
Board is mechanically sound, dimensions are correct and component height does not create mechanical conflicts ✔️ 
IO ports and connectors double checked such that they are accessible when the board is fully assembled 🟡 - **see notes about screw terminals**
No unconnected ground (remove dead copper button checked on Altium polygon object or add stitching via) ✔️ 
Ground pour on top and bottom layers. ✔️ - **no ground plane on top layer but lgtm**
Stitching vias ✔️ 
Length matching for high speed signals and differential pairs 🟡 - **see notes about switch routing**
Proper filter capacitor placement for MCU layout (as close to the pin as possible and in the path of current flow) ✔️ - **n/a**

The layout looks good and functional so far. My suggestions right now are just minor QoL tweaks:
- Add labels to the silkscreen to indicate which switch state enables the terminating resistor
- Add labels to the status LEDs for easier readability when debugging
- Add screw / spring terminals for CAN H/L inputs

And some questions
- CAN2 TX and RX to the Nucleo are thicker traces than CAN1 TX and RX. Is this on purpose?
- Is there a way to route the switches without vias? Anything against running another diff pair out the other side of the input header and putting the switch above/below? Althoug this option may become an issue if we add SMT screw terminals. Conversely, is the diff pair traveling through vias a non-issue?

**Comment by ethanmpeterson** [comment]
- I did not do any high current calculations since the transceivers and LEDs have very low current requirements. The whole board should draw under 50 mA.
- Good call on the terminal blocks for the CAN connectors. I will add those.
- I will also add status LED labels
- I may switch to a DIP switch that has the `ON` label directly on the part to prevent errors from soldering orientation. If I cannot find a switch like that, I will add the silkscreen instead.
- The trace width difference between CAN1 and CAN2 was me forgetting to set it back 0.5mm after getting everything to fit. I will set it back to 0.5mm. I did not make one thicker on purpose. I did however make the Rx and Tx traces relatively wide since I had the space, making them smaller would not affect functionality.
- In regard to avoiding vias on the diff pair routing, I am also unhappy with having vias. I think the only option to fully avoid using them is to route CANH and CANL independently and stack the switch and resistor on top of one another. With that being said, I think this configuration will be fine since we run a very low data rate. Altium's differential pair and length matching utility is more geared towards Ethernet and other faster interfaces with differential pairs. Another option is to use a software controllable termination (see link below from TI). My only concern with this is that we have never done it and it adds a lot of complexity to the board.

https://www.ti.com/lit/ug/tiducf3/tiducf3.pdf?ts=1606502291398

**Comment by llim1** [comment]
I left a 🟡 on IR calculations but it really should have been ✔️ - **N/A**.  That all makes sense. 

Taking a closer look at the datasheet for the switch, it looks like the current component is already a DIP switch with an ON label where the logo is in the 3D view in Altium. (https://www.digikey.ca/en/products/detail/omron-electronics-inc-emc-div/A6S-1104-PH/3102847) 

The TI design would work but agreed, adding MOSFETS and software control seems overkill. This layout is probably fine for our applications but we should really test that.

**Comment by ethanmpeterson** [comment]
> I left a  on IR calculations but it really should have been  - **N/A**. That all makes sense.
> 
> Taking a closer look at the datasheet for the switch, it looks like the current component is already a DIP switch with an ON label where the logo is in the 3D view in Altium. (https://www.digikey.ca/en/products/detail/omron-electronics-inc-emc-div/A6S-1104-PH/3102847)
> 
> The TI design would work but agreed, adding MOSFETS and software control seems overkill. This layout is probably fine for our applications but we should really test that.

Makes sense, I had seen the logo on the 3D model but was unsure if it matched to the switch being on, I will leave it as is then. I agree we will have to test the layout, but my guess is that it should be ok given how low speed CAN is.

**Review by llim1 — APPROVED** [review]
🚢 👍 👨‍💻

**Pull request merged**
