### PR TITLE
Steering Wheel PCB V1

### PR DESCRIPTION
**Pull request by ethanmpeterson**
## Definition of Done
- Schematic passes design review
- PCB is laid out with all the correct IO and connectors for screen and peripherals on the wheel
- Form factor is correct
- Fits inside the CAD model
- Has all (if any) required mounting holes

## TODO
- This schematic is adapted from another general development board design I have been working on.
- Needs a 12 -> 5 V regulator (will look at using another buck design)
- Current design breaks out 20 GPIO pins headers, we should probably pair this down as we figure out exactly what is needed
- Schematic also contains a power management chip which can switch between USB and battery power. I have not yet tested this chip on a design will likely end up removing it unless we are very confident.
- Schematic breaks out two CAN bus transceivers. Will be reduced to just one.

## Other Notes
- This design thus far using exclusively Celestial lib components which have accurate step models for each part. This should allow us to get a precise idea of clearances inside the casing when we get to the layout stage.
- The design includes a debugger built in. The debug MCU can run either ST-Link or BMP firmware as we see fit.
- Debug connection is made through a USB mini port.
- Uses the same STM32F446 chip found on the Mock ECU. For software development, use either the nucleo or Mock ECU PlatformIO templates to get started.

### CODE REVIEW

**Review by llim1 — COMMENTED** [review]
Mostly just needing clarification on some points. We can discuss more in depth at the review meeting! 

MCU Schematic:
* The green box linking to the CAN schematic has 2 nets that go to `CAN_STBY`. Is that on purpose? I may just be unclear on how that link functions.
* Grouping caps together at the bottom is neat but it is not clear where they belong. Some clarification needed, if just for myself haha 
* What is J9 for? 

Power Schematic:
* Consider renaming `IC1` and `IC2` designators something more descriptive of the component, maybe `LDO` or `VR`? 
* Do we want all IO going through the wheel to go through the same header? (CAN, power, etc.) 

Connectors Schematic:
* Molex connectors look good.
* SPI1_NSS is just another name for the SPI CS pin correct?

**Comment by ethanmpeterson** [comment]
> Mostly just needing clarification on some points. We can discuss more in depth at the review meeting!
> 
> MCU Schematic:
> 
> * The green box linking to the CAN schematic has 2 nets that go to `CAN_STBY`. Is that on purpose? I may just be unclear on how that link functions.

This was on accident while I was re arranging the ports, I left the floating wire there. Fixed.

> * Grouping caps together at the bottom is neat but it is not clear where they belong. Some clarification needed, if just for myself haha

I will add a note in the schematic. The 0.1uF caps are bypass caps placed next to VDD pins of the MCU while the other sizes are bulk caps.

> * What is J9 for?

J9 is the SWD Debugger connection.

> Power Schematic:
> 
> * Consider renaming `IC1` and `IC2` designators something more descriptive of the component, maybe `LDO` or `VR`?

I will add a text note in the schematic for what each one is doing. Hesitant to change the designator because any time I re annotate the schematics it will return to the default `IC?` designator given in the celestial library.

> * Do we want all IO going through the wheel to go through the same header? (CAN, power, etc.)

I am good either way but had thought in the meeting we wanted to separate everything.

> 
> Connectors Schematic:
> 
> * Molex connectors look good.
> * SPI1_NSS is just another name for the SPI CS pin correct?

Yes, STM seems to call it NSS in their datasheets so I stuck to their convention in the hopes of making consulting documentation easier.

**Comment by llim1** [comment]
**Connectors**
Misc.
 - Throw in some 5V/GND & 3.3V/GND dedicated 2-pin connectors 

Screen
 - Needs 5V backlight power (2-pins) 
 - Needs 3 gnd pins 

need connector for neopixels (3-pin)
 - 5V power 
 - 5V PWM data signal w/ 470 ohm in series* 
 - 1000uF polarized between power lines 
 
* PWM layout on Nucleo same as arduino just use one of those pins 

need connector for 2x rotary pots ( 2x 3-pin)
 - GND 
 - VDD (3.3v or 5v)
 - Signal 

need connector for shifters (3-pin)
 - Left signal
 - Right signal
 - Shared ground 

**CAN**
Add switch to terminating resistor

**Comment by ethanmpeterson** [comment]
> **Connectors**
> Misc.
> 
> * Throw in some 5V/GND & 3.3V/GND dedicated 2-pin connectors

Done.

> 
> Screen
> 
> * Needs 5V backlight power (2-pins)
> * Needs 3 gnd pins
> 

Done.

> need connector for neopixels (3-pin)
> 
> * 5V power
> * 5V PWM data signal w/ 470 ohm in series*
> * 1000uF polarized between power lines
> 
> * PWM layout on Nucleo same as arduino just use one of those pins

Done.

> 
> need connector for 2x rotary pots ( 2x 3-pin)
> 
> * GND
> * VDD (3.3v or 5v)
> * Signal
> 

Done.

> need connector for shifters (3-pin)
> 
> * Left signal
> * Right signal
> * Shared ground
> 

Done.

> **CAN**
> Add switch to terminating resistor

Done.

**Review by bchampp — COMMENTED** [review]
Changes to schematic look good to me.

**Comment by bchampp** [comment]
image
Can we route this part of the MCU a little bit higher on the board. I think that it would be nice to leave some space under that area for the logo if possible. 

Couple nitpicks:
- Button 1/2 consider changing text sideways to match the alignment.
- I think that we should consider having the order of the bottom connectors instead be Screen Connector, Shifting, Dials (left to right)
   - Puts screen connector closer to the actual screen, we can resize ribbon cable to be pretty short
   - Shifting should be centered because it will wire almost directly to the back plate. (I think it would be nice to coordinate this with danish on where we are embedding the shifting magnets)
   - I think it makes more sense to have the neopixel connector on the other side of all those 2 pin connectors. I'd want our wiring to enter the neopixels from the left side (makes programming easier).

If you want I can reposition the connectors and re-route what breaks

**Comment by ethanmpeterson** [comment]
> Can we route this part of the MCU a little bit higher on the board. I think that it would be nice to leave some space under that area for the logo if possible.

All The routing here is already pretty dense. I will make space for the logo elsewhere instead of moving up the whole MCU layout.

> 
> Couple nitpicks:
> 
> * Button 1/2 consider changing text sideways to match the alignment.

Will do.

> * I think that we should consider having the order of the bottom connectors instead be Screen Connector, Shifting, Dials (left to right)

I can shift that around.

>   * Puts screen connector closer to the actual screen, we can resize ribbon cable to be pretty short
>   * Shifting should be centered because it will wire almost directly to the back plate. (I think it would be nice to coordinate this with danish on where we are embedding the shifting magnets)
>   * I think it makes more sense to have the neopixel connector on the other side of all those 2 pin connectors. I'd want our wiring to enter the neopixels from the left side (makes programming easier).

How does this make programming easier? Does the way you index the LEDs on the strip change depending on what side it is connected? Either way, every connector at the top of the board is fully routed already (Including level shifter and other logic for the neopixels). Could we put this change on the list for the V2?

> 
> If you want I can reposition the connectors and re-route what breaks

**Comment by bchampp** [comment]
Can this get closed? @ethanmpeterson @llim1 @ryan-and

**Comment by ethanmpeterson** [comment]
> Can this get closed? @ethanmpeterson @llim1 @ryan-and 

If someone throws in an approving review I'll merge it.

**Review by llim1 — APPROVED** [review]
This version has been ordered.

**Review by bchampp — APPROVED** [review]

**Comment by bchampp** [comment]
Looks good. @ethanmpeterson can you squash your commits, and leave a merge message indicating this is v1 of the board.

**Pull request merged**
